### ISSUE TITLE
Support for Apache Tinkerpop 3.2.5

### ISSUE THREAD

**Issue by arunkpatra** [awslabs/dynamodb-janusgraph-storage-backend#228] opened 2017-07-19 13:58 UTC
Any timelines for upgrading to Tinkerpop 3.25? Will a PR be welcome?

**Comment by amcp** [comment] 2017-07-19 18:56
I've already got one here, and all we need to do is wait for JanusGraph to do the 0.2.0 release.

**Comment by amcp** [comment] 2017-07-19 18:56
#225

**Comment by amcp** [comment] 2017-07-25 09:08
Duplicate of #226

**Closed by amcp** 2017-07-25 09:08 UTC
