### ISSUE TITLE
Gremlin Server un-responsive

### ISSUE THREAD

**Issue by bradyclo** [awslabs/dynamodb-janusgraph-storage-backend#260] opened 2018-02-28 11:19 UTC
Hello, 

We have followed the solution for the CloudFormation templates, and it appears that nothing is listening on the server on port 8182. This was checked by opening the SSH tunnels to the instance and checking through a browser and also via the instance by curling the localhost on that port. The pre-requisits such as the roles and placing the dynamodb file in the S3 bucket were followed. 

Another observance, the SSH access Security Group parameter is opening port 22 to 0.0.0.0/32, is this intentional? 

Thanks in advance!

**Comment by udayth** [comment] 2018-03-06 06:28
We are running into the same issue. We think the problem is that Gremlin server installation never happens. After all the resources like EC2, VPCs, route tables etc have been created; we believe one or many of these steps are failing. there are no logs we could access to provide you with more info. Also, looks like Java 8 is not being installed which could be causing other failures.


"export SDKMAN_DIR=/usr/local/sdkman && curl -s https://get.sdkman.io | bash && source /usr/local/sdkman/bin/sdkman-init.sh\n"
            - "echo 'export SDKMAN_DIR=/usr/local/sdkman; source /usr/local/sdkman/bin/sdkman-init.sh' > /etc/profile.d/sdkman.sh\n"
            - "yum update && yum upgrade && yum install -y java-1.8.0-openjdk\n"
            - "sdk install maven < /dev/null && set -x\n"
            - "export GREMLIN_SERVER_USERNAME='ec2-user'\n"
            - "export LOG_DIR=/var/log/gremlin-server\n"
            - "export SERVER_DIRNAME=dynamodb-janusgraph-storage-backend-1.2.0\n"
            - "export SERVER_ZIP=${SERVER_DIRNAME}.zip\n"
            - "export PACKAGES_DIR=/usr/local/packages\n"
            - "export INSTALL_DIR=${PACKAGES_DIR}/${SERVER_DIRNAME}\n"
            - "export REPO_ARCHIVE_DIR=/dev/shm/dynamodb-janusgraph-storage-backend-master\n"
            - "mkdir -p ${LOG_DIR} ${INSTALL_DIR}\n"
            - "export SERVICE_SCRIPT=${INSTALL_DIR}/bin/gremlin-server-service.sh\n"
            - "pushd /dev/shm\n"
            - "wget https://github.com/awslabs/dynamodb-janusgraph-storage-backend/archive/master.zip && unzip -q master.zip\n"
            - "pushd ${REPO_ARCHIVE_DIR}\n"
            - "src/test/resources/install-gremlin-server.sh && popd && popd\n"
            - "pushd ${PACKAGES_DIR}\n"
            - "mv ${REPO_ARCHIVE_DIR}/server/${SERVER_DIRNAME} . && rm -rf /dev/shm/* && chmod u+x ${SERVICE_SCRIPT} && ln -s ${SERVICE_SCRIPT} /etc/init.d/gremlin-server && chkconfig --add gremlin-server\n"
            - "export BACKEND_PROPERTIES=${INSTALL_DIR}/conf/gremlin-server/dynamodb.properties\n"
            - "aws s3 cp "
            - Ref: "StorageBackendPropertiesFileS3Url"
            - " ${BACKEND_PROPERTIES}\n"
            - "chown -R ${GREMLIN_SERVER_USERNAME}:${GREMLIN_SERVER_USERNAME} ${LOG_DIR} ${INSTALL_DIR}\n"
            - "ln -s ${INSTALL_DIR}/conf /home/ec2-user/conf && chmod a+r /home/ec2-user/conf\n"
            - "service gremlin-server start\n\n"

**Comment by udayth** [comment] 2018-03-06 07:39
BTW: If we run all the needed steps/software installations 'manually' on the instance; things work. Cloudformation template (the above steps specifically) is broken.

**Comment by amcp** [comment] 2018-03-09 21:28
@bradyclo we default to no access via SSH because you, the customer needs to determine which host you will SSH from and modify the mask. I will try starting up an instance to see if I can identify the problem.

**Comment by amcp** [comment] 2018-03-09 21:28
@udayth If Java 8 is not being installed, that is a problem. I will confirm/refute and report here.

**Comment by udayth** [comment] 2018-03-14 05:47
@amcp Thanks for the response. Any chance you had some time to look into this? Any help is appreciated.

**Comment by danieljue** [comment] 2018-03-15 19:52
I am having a similar issue where the cloud formation script executes the shell commands only partially, I still can't get the gremlin service to install.  I have created a manual.sh file that I copy to the EC2 instance, in order to play with getting it to run.  Here is my manual.sh:`#!/bin/bash
  export SDKMAN_DIR=/usr/local/sdkman && curl -s https://get.sdkman.io | bash && source /usr/local/sdkman/bin/sdkman-init.sh
  echo 'export SDKMAN_DIR=/usr/local/sdkman; source /usr/local/sdkman/bin/sdkman-init.sh' > /etc/profile.d/sdkman.sh
  yum update && yum upgrade && yum install -y java-1.8.0-openjdk
  yum remove java-1.7.0-openjdk -y
  sdk install maven < /dev/null && set -x
  export GREMLIN_SERVER_USERNAME='ec2-user'
  export LOG_DIR=/var/log/gremlin-server
  export SERVER_DIRNAME=dynamodb-janusgraph-storage-backend-1.2.0
  export SERVER_ZIP=${SERVER_DIRNAME}.zip
  export PACKAGES_DIR=/usr/local/packages
  export INSTALL_DIR=${PACKAGES_DIR}/${SERVER_DIRNAME}
  export REPO_ARCHIVE_DIR=/dev/shm/dynamodb-janusgraph-storage-backend-master
  mkdir -p ${LOG_DIR} ${INSTALL_DIR}
  export SERVICE_SCRIPT=${INSTALL_DIR}/bin/gremlin-server-service.sh
  pushd /dev/shm
  wget https://github.com/awslabs/dynamodb-janusgraph-storage-backend/archive/master.zip && unzip -q master.zip
  pushd ${REPO_ARCHIVE_DIR}
  src/test/resources/install-gremlin-server.sh && popd && popd
  pushd ${PACKAGES_DIR}
  mv ${REPO_ARCHIVE_DIR}/server/${SERVER_DIRNAME} . && rm -rf /dev/shm/* && chmod u+x ${SERVICE_SCRIPT} && ln -s ${SERVICE_SCRIPT} /etc/init.d/gremlin-server && chkconfig --add gremlin-server
  export BACKEND_PROPERTIES=${INSTALL_DIR}/conf/gremlin-server/dynamodb.properties
  aws s3 cp s3://ironnet-labs-cognition/dynamodb.properties ${BACKEND_PROPERTIES}
  chown -R ${GREMLIN_SERVER_USERNAME}:${GREMLIN_SERVER_USERNAME} ${LOG_DIR} ${INSTALL_DIR}
  ln -s ${INSTALL_DIR}/conf /home/ec2-user/conf && chmod a+r /home/ec2-user/conf
  service gremlin-server start
`


Here is the output from running this manual.sh as the EC2 user on the EC2 instance, note that I choose 'N' when asked to overwrite the unzipped  master.zip files.  There are some maven errors about checkstyle not having permmisions to some dirs.

`[ec2-user@ip-10-0-0-68 ~]$ ./manual.sh 

                                -+syyyyyyys:
                            `/yho:`       -yd.
                         `/yh/`             +m.
                       .oho.                 hy                          .`
                     .sh/`                   :N`                `-/o`  `+dyyo:.
                   .yh:`                     `M-          `-/osysoym  :hs` `-+sys:      hhyssssssssy+
                 .sh:`                       `N:          ms/-``  yy.yh-      -hy.    `.N-````````+N.
               `od/`                         `N-       -/oM-      ddd+`     `sd:     hNNm        -N:
              :do`                           .M.       dMMM-     `ms.      /d+`     `NMMs       `do
            .yy-                             :N`    ```mMMM.      -      -hy.       /MMM:       yh
          `+d+`           `:/oo/`       `-/osyh/ossssssdNMM`           .sh:         yMMN`      /m.
         -dh-           :ymNMMMMy  `-/shmNm-`:N/-.``   `.sN            /N-         `NMMy      .m/
       `oNs`          -hysosmMMMMydmNmds+-.:ohm           :             sd`        :MMM/      yy
      .hN+           /d:    -MMMmhs/-.`   .MMMh   .ss+-                 `yy`       sMMN`     :N.
     :mN/           `N/     `o/-`         :MMMo   +MMMN-         .`      `ds       mMMh      do
    /NN/            `N+....--:/+oooosooo+:sMMM:   hMMMM:        `my       .m+     -MMM+     :N.
   /NMo              -+ooooo+/:-....`...:+hNMN.  `NMMMd`        .MM/       -m:    oMMN.     hs
  -NMd`                                    :mm   -MMMm- .s/     -MMm.       /m-   mMMd     -N.
 `mMM/                                      .-   /MMh. -dMo     -MMMy        od. .MMMs..---yh
 +MMM.                                           sNo`.sNMM+     :MMMM/        sh`+MMMNmNm+++-
 mMMM-                                           /--ohmMMM+     :MMMMm.       `hyymmmdddo
 MMMMh.                  ````                  `-+yy/`yMMM/     :MMMMMy       -sm:.``..-:-.`
 dMMMMmo-.``````..-:/osyhddddho.           `+shdh+.   hMMM:     :MmMMMM/   ./yy/` `:sys+/+sh/
 .dMMMMMMmdddddmmNMMMNNNNNMMMMMs           sNdo-      dMMM-  `-/yd/MMMMm-:sy+.   :hs-      /N`
  `/ymNNNNNNNmmdys+/::----/dMMm:          +m-         mMMM+ohmo/.` sMMMMdo-    .om:       `sh
     `.-----+/.`       `.-+hh/`         `od.          NMMNmds/     `mmy:`     +mMy      `:yy.
           /moyso+//+ossso:.           .yy`          `dy+:`         ..       :MMMN+---/oys:
         /+m:  `.-:::-`               /d+                                    +MMMMMMMNh:`
        +MN/                        -yh.                                     `+hddhy+.
       /MM+                       .sh:
      :NMo                      -sh/
     -NMs                    `/yy:
    .NMy                  `:sh+.
   `mMm`               ./yds-
  `dMMMmyo:-.````.-:oymNy:`
  +NMMMMMMMMMMMMMMMMms:`
    -+shmNMMMNmdy+:`


                                                                 Now attempting installation...


Looking for a previous installation of SDKMAN...
SDKMAN found.

======================================================================================================
 You already have SDKMAN installed.
 SDKMAN was found at:

    /usr/local/sdkman

 Please consider running the following if you need to upgrade.

    $ sdk selfupdate force

======================================================================================================

./manual.sh: line 3: /etc/profile.d/sdkman.sh: Permission denied
Loaded plugins: priorities, update-motd, upgrade-helper
You need to be root to perform this command.
Loaded plugins: priorities, update-motd, upgrade-helper
You need to be root to perform this command.

Stop! maven 3.5.2 is already installed.
+ export GREMLIN_SERVER_USERNAME=ec2-user
+ GREMLIN_SERVER_USERNAME=ec2-user
+ export LOG_DIR=/var/log/gremlin-server
+ LOG_DIR=/var/log/gremlin-server
+ export SERVER_DIRNAME=dynamodb-janusgraph-storage-backend-1.2.0
+ SERVER_DIRNAME=dynamodb-janusgraph-storage-backend-1.2.0
+ export SERVER_ZIP=dynamodb-janusgraph-storage-backend-1.2.0.zip
+ SERVER_ZIP=dynamodb-janusgraph-storage-backend-1.2.0.zip
+ export PACKAGES_DIR=/usr/local/packages
+ PACKAGES_DIR=/usr/local/packages
+ export INSTALL_DIR=/usr/local/packages/dynamodb-janusgraph-storage-backend-1.2.0
+ INSTALL_DIR=/usr/local/packages/dynamodb-janusgraph-storage-backend-1.2.0
+ export REPO_ARCHIVE_DIR=/dev/shm/dynamodb-janusgraph-storage-backend-master
+ REPO_ARCHIVE_DIR=/dev/shm/dynamodb-janusgraph-storage-backend-master
+ mkdir -p /var/log/gremlin-server /usr/local/packages/dynamodb-janusgraph-storage-backend-1.2.0
+ export SERVICE_SCRIPT=/usr/local/packages/dynamodb-janusgraph-storage-backend-1.2.0/bin/gremlin-server-service.sh
+ SERVICE_SCRIPT=/usr/local/packages/dynamodb-janusgraph-storage-backend-1.2.0/bin/gremlin-server-service.sh
+ pushd /dev/shm
/dev/shm ~
+ wget https://github.com/awslabs/dynamodb-janusgraph-storage-backend/archive/master.zip
--2018-03-15 19:41:52--  https://github.com/awslabs/dynamodb-janusgraph-storage-backend/archive/master.zip
Resolving github.com (github.com)... 192.30.253.112, 192.30.253.113
Connecting to github.com (github.com)|192.30.253.112|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/awslabs/dynamodb-janusgraph-storage-backend/zip/master [following]
--2018-03-15 19:41:52--  https://codeload.github.com/awslabs/dynamodb-janusgraph-storage-backend/zip/master
Resolving codeload.github.com (codeload.github.com)... 192.30.253.120, 192.30.253.121
Connecting to codeload.github.com (codeload.github.com)|192.30.253.120|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/zip]
Saving to: ‘master.zip.1’

master.zip.1                                      [ <=>                                                                                           ] 752.65K  --.-KB/s    in 0.1s    

2018-03-15 19:41:53 (7.25 MB/s) - ‘master.zip.1’ saved [770709]

+ unzip -q master.zip
replace dynamodb-janusgraph-storage-backend-master/.gitignore? [y]es, [n]o, [A]ll, [N]one, [r]ename: n
replace dynamodb-janusgraph-storage-backend-master/.travis.yml? [y]es, [n]o, [A]ll, [N]one, [r]ename: N
+ pushd /dev/shm/dynamodb-janusgraph-storage-backend-master
/dev/shm/dynamodb-janusgraph-storage-backend-master /dev/shm ~
+ src/test/resources/install-gremlin-server.sh
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (validate) on project dynamodb-janusgraph-storage-backend: Unable to create output stream: /dev/shm/dynamodb-janusgraph-storage-backend-master/target/checkstyle-result.xml: /dev/shm/dynamodb-janusgraph-storage-backend-master/target/checkstyle-result.xml (Permission denied) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
+ pushd /usr/local/packages
/usr/local/packages /dev/shm/dynamodb-janusgraph-storage-backend-master /dev/shm ~
+ mv /dev/shm/dynamodb-janusgraph-storage-backend-master/server/dynamodb-janusgraph-storage-backend-1.2.0 .
mv: cannot stat ‘/dev/shm/dynamodb-janusgraph-storage-backend-master/server/dynamodb-janusgraph-storage-backend-1.2.0’: No such file or directory
+ export BACKEND_PROPERTIES=/usr/local/packages/dynamodb-janusgraph-storage-backend-1.2.0/conf/gremlin-server/dynamodb.properties
+ BACKEND_PROPERTIES=/usr/local/packages/dynamodb-janusgraph-storage-backend-1.2.0/conf/gremlin-server/dynamodb.properties
+ aws s3 cp s3://ironnet-labs-cognition/dynamodb.properties /usr/local/packages/dynamodb-janusgraph-storage-backend-1.2.0/conf/gremlin-server/dynamodb.properties
download: s3://ironnet-labs-cognition/dynamodb.properties to dynamodb-janusgraph-storage-backend-1.2.0/conf/gremlin-server/dynamodb.properties
+ chown -R ec2-user:ec2-user /var/log/gremlin-server /usr/local/packages/dynamodb-janusgraph-storage-backend-1.2.0
+ ln -s /usr/local/packages/dynamodb-janusgraph-storage-backend-1.2.0/conf /home/ec2-user/conf
+ chmod a+r /home/ec2-user/conf
+ service gremlin-server start
gremlin-server: unrecognized service
[ec2-user@ip-10-0-0-68 ~]$ 
`

**Comment by danieljue** [comment] 2018-03-15 22:04
It seems using yum to install mvn pulls in Java 1.7 as a dep.  Yum removing Java 1.7 removes Maven as a dep!

**Comment by danieljue** [comment] 2018-03-15 22:45
Update, I was able to get the server to install and run.  I added a line to install java via SDKMAN.  Here is the portion of the script you can put in dynamodb-janusgraph-storage-backend-cfn.yaml, replacing the existing one:

`     
 UserData:
        Fn::Base64:
          Fn::Join:
          - ''
          - - "#!/bin/bash\n"
            - "export SDKMAN_DIR=/usr/local/sdkman && curl -s https://get.sdkman.io | bash && source /usr/local/sdkman/bin/sdkman-init.sh\n"
            - "echo 'export SDKMAN_DIR=/usr/local/sdkman; source /usr/local/sdkman/bin/sdkman-init.sh' > /etc/profile.d/sdkman.sh\n"
            - "yum update -y && yum upgrade -y && yum install -y java-1.8.0-openjdk > /home/ec2-user/yumupdates.log\n"
            - "yum remove -y java-1.7.0-openjdk > /home/ec2-user/yumremovejava7.log\n"
            - "java -version > /home/ec2-user/java-version-before-sdkmvn.log\n"
            - "sdk install java < /dev/null\n"
            - "sdk current java > /home/ec2-user/java-version-from-sdkman.log\n"
            - "sdk install maven < /dev/null && set -x\n"
            - "mvn -version > /home/ec2-user/maven-installation-settings.log\n"
            - "export GREMLIN_SERVER_USERNAME='ec2-user'\n"
            - "export LOG_DIR=/var/log/gremlin-server\n"
            - "export SERVER_DIRNAME=dynamodb-janusgraph-storage-backend-1.2.0\n"
            - "export SERVER_ZIP=${SERVER_DIRNAME}.zip\n"
            - "export PACKAGES_DIR=/usr/local/packages\n"
            - "export INSTALL_DIR=${PACKAGES_DIR}/${SERVER_DIRNAME}\n"
            - "export REPO_ARCHIVE_DIR=/dev/shm/dynamodb-janusgraph-storage-backend-master\n"
            - "mkdir -p ${LOG_DIR} ${INSTALL_DIR}\n"
            - "export SERVICE_SCRIPT=${INSTALL_DIR}/bin/gremlin-server-service.sh\n"
            - "pushd /dev/shm\n"
            - "wget https://github.com/awslabs/dynamodb-janusgraph-storage-backend/archive/master.zip && unzip -q master.zip\n"
            - "pushd ${REPO_ARCHIVE_DIR}\n"
            - "src/test/resources/install-gremlin-server.sh > /home/ec2-user/gremlin-server-installation.log && popd && popd\n"
            - "pushd ${PACKAGES_DIR}\n"
            - "mv ${REPO_ARCHIVE_DIR}/server/${SERVER_DIRNAME} . && rm -rf /dev/shm/* && chmod u+x ${SERVICE_SCRIPT} && ln -s ${SERVICE_SCRIPT} /etc/init.d/gremlin-server && chkconfig --add gremlin-server\n"
            - "export BACKEND_PROPERTIES=${INSTALL_DIR}/conf/gremlin-server/dynamodb.properties\n"
            - "aws s3 cp "
            - Ref: "StorageBackendPropertiesFileS3Url"
            - " ${BACKEND_PROPERTIES}\n"
            - "chown -R ${GREMLIN_SERVER_USERNAME}:${GREMLIN_SERVER_USERNAME} ${LOG_DIR} ${INSTALL_DIR}\n"
            - "ln -s ${INSTALL_DIR}/conf /home/ec2-user/conf && chmod a+r /home/ec2-user/conf\n"
            - "service gremlin-server start > /home/ec2-user/gremlin-server-start.log\n\n"`

**Comment by sandeepdoctily** [comment] 2018-03-16 03:29
One more issue I faced when installing on t2.micro is space on "/dev/shm" which causes failure of script. Can we move to "/tmp" so that it can work on all types of instances?

**Comment by sandeepdoctily** [comment] 2018-03-16 08:46
@danieljue @udayth @amcp 

I can confirm this that the template is now working for t2.micro instance as well when I change the "/dev/shm" to "/tmp/shm".

Thanks for help.

**Comment by amcp** [comment] 2018-03-16 21:47
fixed in #263

**Closed by amcp** 2018-03-16 21:47 UTC
